/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSongsRouteImport } from './routes/api/songs'
import { Route as ApiArtistsRouteImport } from './routes/api/artists'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ChartsSongsPopularRouteImport } from './routes/charts/songs/popular'
import { Route as ChartsSongsLatestRouteImport } from './routes/charts/songs/latest'
import { Route as ChartsArtistsPopularRouteImport } from './routes/charts/artists/popular'
import { Route as ChartsArtistsFollowersRouteImport } from './routes/charts/artists/followers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'

const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSongsRoute = ApiSongsRouteImport.update({
  id: '/api/songs',
  path: '/api/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtistsRoute = ApiArtistsRouteImport.update({
  id: '/api/artists',
  path: '/api/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ChartsSongsPopularRoute = ChartsSongsPopularRouteImport.update({
  id: '/charts/songs/popular',
  path: '/charts/songs/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsSongsLatestRoute = ChartsSongsLatestRouteImport.update({
  id: '/charts/songs/latest',
  path: '/charts/songs/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsArtistsPopularRoute = ChartsArtistsPopularRouteImport.update({
  id: '/charts/artists/popular',
  path: '/charts/artists/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsArtistsFollowersRoute = ChartsArtistsFollowersRouteImport.update({
  id: '/charts/artists/followers',
  path: '/charts/artists/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/app/polar/portal',
  path: '/app/polar/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/charts/artists/followers': typeof ChartsArtistsFollowersRoute
  '/charts/artists/popular': typeof ChartsArtistsPopularRoute
  '/charts/songs/latest': typeof ChartsSongsLatestRoute
  '/charts/songs/popular': typeof ChartsSongsPopularRoute
  '/app': typeof AuthAppIndexRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/charts/artists/followers': typeof ChartsArtistsFollowersRoute
  '/charts/artists/popular': typeof ChartsArtistsPopularRoute
  '/charts/songs/latest': typeof ChartsSongsLatestRoute
  '/charts/songs/popular': typeof ChartsSongsPopularRoute
  '/app': typeof AuthAppIndexRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_static': typeof StaticRouteRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/charts/artists/followers': typeof ChartsArtistsFollowersRoute
  '/charts/artists/popular': typeof ChartsArtistsPopularRoute
  '/charts/songs/latest': typeof ChartsSongsLatestRoute
  '/charts/songs/popular': typeof ChartsSongsPopularRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/artists'
    | '/api/songs'
    | '/api/auth/$'
    | '/charts/artists/followers'
    | '/charts/artists/popular'
    | '/charts/songs/latest'
    | '/charts/songs/popular'
    | '/app'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/polar/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/artists'
    | '/api/songs'
    | '/api/auth/$'
    | '/charts/artists/followers'
    | '/charts/artists/popular'
    | '/charts/songs/latest'
    | '/charts/songs/popular'
    | '/app'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/polar/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_static'
    | '/api/artists'
    | '/api/songs'
    | '/api/auth/$'
    | '/charts/artists/followers'
    | '/charts/artists/popular'
    | '/charts/songs/latest'
    | '/charts/songs/popular'
    | '/_auth/app/'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/_auth/app/polar/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StaticRouteRoute: typeof StaticRouteRoute
  ApiArtistsRoute: typeof ApiArtistsRoute
  ApiSongsRoute: typeof ApiSongsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ChartsArtistsFollowersRoute: typeof ChartsArtistsFollowersRoute
  ChartsArtistsPopularRoute: typeof ChartsArtistsPopularRoute
  ChartsSongsLatestRoute: typeof ChartsSongsLatestRoute
  ChartsSongsPopularRoute: typeof ChartsSongsPopularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/songs': {
      id: '/api/songs'
      path: '/api/songs'
      fullPath: '/api/songs'
      preLoaderRoute: typeof ApiSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artists': {
      id: '/api/artists'
      path: '/api/artists'
      fullPath: '/api/artists'
      preLoaderRoute: typeof ApiArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/charts/songs/popular': {
      id: '/charts/songs/popular'
      path: '/charts/songs/popular'
      fullPath: '/charts/songs/popular'
      preLoaderRoute: typeof ChartsSongsPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/songs/latest': {
      id: '/charts/songs/latest'
      path: '/charts/songs/latest'
      fullPath: '/charts/songs/latest'
      preLoaderRoute: typeof ChartsSongsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/artists/popular': {
      id: '/charts/artists/popular'
      path: '/charts/artists/popular'
      fullPath: '/charts/artists/popular'
      preLoaderRoute: typeof ChartsArtistsPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/artists/followers': {
      id: '/charts/artists/followers'
      path: '/charts/artists/followers'
      fullPath: '/charts/artists/followers'
      preLoaderRoute: typeof ChartsArtistsFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StaticRouteRoute: StaticRouteRoute,
  ApiArtistsRoute: ApiArtistsRoute,
  ApiSongsRoute: ApiSongsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ChartsArtistsFollowersRoute: ChartsArtistsFollowersRoute,
  ChartsArtistsPopularRoute: ChartsArtistsPopularRoute,
  ChartsSongsLatestRoute: ChartsSongsLatestRoute,
  ChartsSongsPopularRoute: ChartsSongsPopularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
